//
//  OperatorDummy.swift
//  Rainbow Six Siege Operators
//
//  Created by Cesa Anwar on 18/06/20.
//  Copyright © 2020 Cesa Anwar. All rights reserved.
//

import UIKit

var operators: [Operator] = [
    Operator(codename: "Fuze", role: "Area-Denial, Disable, Flank", icon: UIImage(named: "fuze")!, picture: UIImage(named: "r6-operators-list-fuze")!, side: 0, bio: "\u{22}Chaos is only an enemy if you’re unable to adapt.\u{22} \n\nGrowing up in a military family in Samarkand, Uzbekistan, Shuhrat Kessikbayev immigrated to Russia shortly before the fall of the Soviet Union. From an early age Kessikbayev displayed an aptitude for science. His interest in mechanical engineering was honed in the military where he also trained as a machinist. Kessikbayev has applied these skills in numerous engineering projects, including his own weapon, and his ability to improvise in the field with scrap materials and minimal tools has made him a legend among his fellow recruits. This is one of the key reasons he is an asset to Rainbow Operations. During his time in the 27th Motor Rifle Brigade he excelled as a sharpshooter and has extensive weapon knowledge. Deployment within the Spetsnaz is confirmed, however, all operation details remain classified. Kessikbayev is fluent in Uzbek, Russian, Ukrainian, and English."),
    Operator(codename: "Thermite", role: "Back-Line, Hard-Breach", icon: UIImage(named: "thermite")!, picture: UIImage(named: "r6-operators-list-thermite")!, side: 0, bio: "\u{22}You see a wall, I see an opportunity.\u{22}\n\nTrace joined the Corps straight out of high school, making him a fourth-generation Marine. Following his first tour of Iraq, he obtained enough experience to volunteer as an explosive ordnance disposal technician. After his second tour of Iraq, Trace returned to the U.S., enrolled in university, and earned a Bachelor of Science in Chemistry. He brought his experience and skills to the FBI, where he spent a number of years as a field agent within the Hazardous Materials Response Unit. Seeking more dynamic environments, Trace transferred into FBI SWAT, where he excelled at developing new barricade protocols. He then earned a spot in Rainbow where he’s shown further interest in research and development on gadget upgrades. Trace’s hometown of Plano has a major concentration of Chinese Americans, and as such Trace has conversational level of Mandarin."),
    Operator(codename: "Thatcher", role: "Back-Line, Disable", icon: UIImage(named: "thatcher")!, picture: UIImage(named: "r6-operators-list-thatcher")!, side: 0, bio: "\u{22}What you can feel, what you can touch – those are the things that are real. Everything else is just a distraction.\u{22}\n\nBaker comes from a long line of dockworkers and soldiers. At the age of eighteen he enlisted for active military duty despite family pressure to join the family trade as a stevedore. Immediately thrown into politically-charged conflicts, Baker’s performance was exemplary. Further training and another conflict gave him a Distinguished Flying Cross and Conspicuous Gallantry Cross. His keen sense of observation and decisive manner, combined with his close-quarter combat techniques, made him invaluable on VIP protection detail.\n\nWith extensive field experience and proficiency in SAS tactics, Baker is a critical asset to any Rainbow operation. He has honed his expertise with protective measures and electronic counter-measures and frequently works with engineers to advance the equipment. As a Warrant Officer Class 1 (Regimental Sergeant Major) Baker serves as a respected and effective mentor to new recruits. Baker maintains his agility training, continuing abseiling, and has broken numerous mountain climbing records."),
    Operator(codename: "Blackbeard", role: "Back-Line, Covering-Fire, Shield", icon: UIImage(named: "blackbeard")!, picture: UIImage(named: "r6-operators-list-blackbeard")!, side: 0, bio: "\u{22}I’m a diver. We’re used to seeing threats through a layer of tempered glass.\u{22}\n\nInstead of following the family tradition in the medical sciences, Jenson joined the US Navy. His early years in the Boy Scouts and the United States Naval Sea Cadet Corps (Blue Angels Squadron) solidified his desire to serve his country and see the world. Joining the military offered him the ideal opportunity to pursue an academic education while learning a wide range of skills that fueled his adventurous spirit. After his initial military stint, Jenson focused on the US Navy SEALs as his ultimate career goal. Driven to succeed in his profession and his private life, he has climbed Mount Everest, participated in US sailing championships, and has sailed around the world on several occasions."),
    Operator(codename: "Jackal", role: "Anti-Roam, Intel-Gatherer", icon: UIImage(named: "jackal")!, picture: UIImage(named: "r6-operators-list-jackal")!, side: 0, bio: "\u{22}You can’t escape me, but that doesn’t mean you won’t try.\u{22}\n\nAl-Hassar’s early years are unclear due to incomplete foster care records. Eventually released into the care of his older brother, Faisal, the two of them were absent from official records for several years until Faisal’s unsolved murder once again left Al-Hassar without a home. Being guided through the tragedy by a sympathetic police officer solidified Al-Hassar’s resolve to find his brother’s murderer and he joined the Cuerpo Nacional de Policía the day he turned eighteen. Fast-tracked through the academy with the help of his mentor, Al-Hassar stood out as a quick learner with exceptional lateral thinking. His dogged determination resolved a number of criminal investigations but, unfortunately, the case of his brother’s murder remains open. Tagged by the Grupo Especial de Operaciones for further training, Al-Hassar excelled in off-road driving, abseiling, marksmanship, and knowledge of terrorist groups. He is a frequent guest lecturer and part-time instructor at the CNP academy."),
    
    Operator(codename: "Mute", role: "Anti-Hard-Breach, Intel-Denier, Secure", icon: UIImage(named: "mute")!, picture: UIImage(named: "r6-operators-list-mute")!, side: 1, bio: "\u{22}People think my codename is because I don’t like to talk. Maybe I just don’t like you.\u{22}\n\nAn exceptional and well-rounded student, Chandar was one of the youngest accepted into the University of Cambridge. He majored in electronics and computer engineering, completing an internship at a prestigious tech company where he contributed to the design and function of security system prototypes. His ingenuity caught the attention of Britain’s national security office, the Government Communications Headquarters (GCHQ). Having demonstrated acuity in code breaking, Chandar became an intelligence officer within the signals intelligence (SIGINT) unit. He continues to contribute to the applied technical research team and has recently expanded his field of study to include learning Korean."),
    Operator(codename: "Smoke", role: "Anchor, Area-Denial, Secure", icon: UIImage(named: "smoke")!, picture: UIImage(named: "r6-operators-list-smoke")!, side: 1, bio: "\u{22}Sure, I care about the environment. Immediately around me, anyway.\u{22}\n\nThough Porter wasn’t an exceptional student, aptitude tests revealed his propensity for sciences. Encouraged by faculty and his parents, he was able to follow a more unorthodox manner of education with tutors, home-schooling, and field science. He flourished in this break from formal classroom studies and quickly developed his skills in chemistry, biology, and math. Uninterested in pursuing a formal university education, Porter forged a fake ID and enlisted in the British Army. Though the rigidity of army rules wasn’t always a good fit, it was offset by the diverse range of training and experiences army life gave him. While he has been reprimanded for breaking rules, his superiors quickly recognized both his innovation and strategic perspective. He was then encouraged to join the SAS. Porter prefers to acquire knowledge and skills, such as language and music, in his own way and does not excel in a formal training capacity."),
    Operator(codename: "JÄGER", role: "Roam, Secure", icon: UIImage(named: "jager")!, picture: UIImage(named: "r6-operators-list-jager")!, side: 1, bio: "\u{22}Birthdays. Proposals. These should be surprises. No one wants a grenade to the face.\u{22}\n\nRaised by his uncle, a mechanic with the Bundespolizei (BPOL) Aviation Group, Streicher was around engines and motors at an early age. While he demonstrated skills in mechanics, it didn’t hold the challenge that he was looking for. Since he had an affinity for complex machinery, his uncle encouraged him to study aeronautical engineering at university, but strict academic form was an uncomfortable fit for him. So while Streicher’s grades were acceptable, he had a tendency toward restless antics. Following his hobby and passion in flying, he spent considerable time around pilots and aircraft. Private corporations sought him out, but Streicher joined BPOL-Aviation Group because it offered him unique challenges, the opportunity to fly and to serve his country. Almost immediately, Streicher began designing defensive weapon systems for BPOL including a ground-based Active Defense System (ADS) prototype. It was this prototype that caught the attention of GSG 9 and Rainbow."),
    Operator(codename: "Mozzie", role: "Intel-Denier, Intel-Gatherer, Secure", icon: UIImage(named: "mozzie")!, picture: UIImage(named: "r6-operators-list-mozzie")!, side: 1, bio: "\u{22}C’mon, I'm not here to f*** spiders.\u{22}\n\nRight after Year 10, Max Goose applied to enter the Australian Defence Force Academy, later working in Combat & Security. He joined an infantry regiment that incorporated dirt bikes and all-terrain vehicles in their reconnaissance operations. Goose excelled in land navigation and became the two-wheeler expert in raids, scouting, and convoy operations.\n\nFollowing Operation Catalyst, he was handpicked to join the Special Air Service Regiment (SASR), so long as he passed selection and refrained from talking back. His specialized off-road skillsets and quick thinking were highly prized, even though his driving style appeared reckless. He deployed to Operation Slipper and served until the operation’s conclusion. He later received the National Emergency Medal for saving firefighters during the Esperance bushfires.\n\nGoose is a calculated daredevil who loves testing upcoming military stealth bikes, but he says there’s no bigger honor than being asked to join Rainbow Six."),
    Operator(codename: "Pulse", role: "Intel-Gatherer, Roam", icon: UIImage(named: "pulse")!, picture: UIImage(named: "r6-operators-list-pulse")!, side: 1, bio: "\u{22}The heart is just a motor. Like any machine, it can be fine-tuned.\u{22}\n\nBorn on Seymour Johnson Air Force Base, Estrada was raised on bases across the US and internationally, in Germany, Turkey, and Japan. His father was a pilot and his mother was a classified Senior Intelligence Officer. Estrada demonstrated acumen for science at an early age and was quickly moved into an advanced curriculum. His focus on Forensic Science and Biochemistry made him a perfect fit for the Biometrics Program with the FBI, which he joined as their youngest intern. He secured his role as an agent and was soon recruited into SWAT, working both in the field and in the FBI Lab. Estrada’s high emotional intelligence led him to join the FBI’s Hostage Rescue Team (HRT) where he excelled in crisis management and negotiation tactics. His knowledge of behavioral biometrics led to the creation of the Cardiac Sensor, along with several other prototypes which he continues to refine."),
]
